### ISSUE TITLE
Неверные переводы 

### ISSUE THREAD

**Issue by Azilagor** [munnificent/Kaznpuball#1]
![image](https://github.com/munnificent/Kaznpuball/assets/67140643/3f4b19ee-0c07-47a2-bc5e-32b43572e4ec)

![image](https://github.com/munnificent/Kaznpuball/assets/67140643/c3ff4e5b-5947-4388-913f-8bcf908a2ffa)

Нужны переводы Right и Wrong для верного клиентского опыта 
По моему скромному мнению эти обозначения можно убрать и оставить  только цветовое обозначение Правильного и Неправильного заполнения

**Comment by munnificent** [comment]
Да хотел перевести, но пока разбирался с PWA, в падлу стало. Потом когда запилю ещё один сервис, этот поправлю  😋
